baseURL = 'https://techni-couv91.fr/'
languageCode = 'fr-FR'
title = "Couvreur 91 TechniCouv artisan Couvreur dans l'Essonne"
theme = "mister"




[params]

    description = "Couvreur 91 TechniCouv Le technicien de la Couverture Entreprise de couverture dans l'Essonne"

    author="Randy ROBERT"
    
    [params.adresse]
    adresseprincipale = "7 Chemin des Galetteries 91310 Leuville Sur Orge"
    logo = "/images/logos/logo techi couv 91 couvreur dans l'essonne .webp"
    license = "Depuis 2009 à votre service dans l'Essonne Technicouv "



[params.phone]
    phonemobile = "07 85 88 47 86"
    phonemobilelink = "0785884786"
    phonefixe = "09 73 73 86 94"
    phonefixelink = "0973738694"



[[menu.footer]]
name = "Mentions Légales"
url = "/mentions-legales"

[[menu.footer]]
name = "Protection des données"
url = "/données"

[[menu.footer]]
name = "Plan du Site"
url = "/plan"

